version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.7.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.7.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1

  kafka-init-topics:
    image: confluentinc/cp-kafka:7.7.0
    container_name: kafka-init-topics
    depends_on:
      - kafka
    entrypoint: ["/bin/sh", "-c"]
    command: |
      echo "Waiting for Kafka to be ready..."
      cub kafka-ready -b kafka:9092 1 30
      echo "Creating Kafka topics..."
      kafka-topics --bootstrap-server kafka:9092 --create --topic stock-updates --partitions 3 --replication-factor 1 --if-not-exists
      kafka-topics --bootstrap-server kafka:9092 --create --topic orders --partitions 3 --replication-factor 1 --if-not-exists
      echo "Topics created."
    environment:
      KAFKA_BROKER_ID: ignored
      KAFKA_ZOOKEEPER_CONNECT: ignored